"use client";
import Link from "next/link";
import type { Project } from "@/data/portfolio";
import { animated, useSpring } from "@react-spring/web";
import { useEffect, useRef, useState, type ReactNode } from "react";
type StageProps = { number: string; title: string; english: string; sentence: string; children: ReactNode };
function Stage({ number, title, english, sentence, children }: StageProps) {
  const ref = useRef<HTMLElement>(null); const [active, setActive] = useState(false);
  const spring = useSpring({ opacity: active ? 1 : 0.38, y: active ? 0 : 18, config: { tension: 190, friction: 25 } });
  useEffect(() => { const node = ref.current; if (!node) return; const observer = new IntersectionObserver(([entry]) => setActive(entry.isIntersecting), { threshold: 0.3 }); observer.observe(node); return () => observer.disconnect(); }, []);
  return <section ref={ref} className="grid min-h-[78svh] items-center gap-10 border-t border-line py-section lg:grid-cols-12 lg:gap-16"><div className="lg:col-span-4"><p className="font-mono text-xs tracking-widest text-accent">{number} / 10 · {english}</p><h2 className="mt-5 text-heading leading-display tracking-tight">{title}</h2><p className="mt-5 max-w-sm text-lg leading-relaxed text-muted">{sentence}</p></div><animated.div style={{ opacity: spring.opacity, transform: spring.y.to(value => "translate3d(0," + value + "px,0)") }} className="min-w-0 lg:col-span-8">{children}</animated.div></section>;
}
function Boxes({ items, accent = false }: { items: string[]; accent?: boolean }) { return <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map((item, index) => <div key={item} className={accent && index === items.length - 1 ? "border border-accent p-4" : "border border-line p-4"}><span className="font-mono text-xs text-accent">{String(index + 1).padStart(2, "0")}</span><p className="mt-5 text-base">{item}</p></div>)}</div>; }
function Flow({ items }: { items: string[] }) { return <div className="flex flex-wrap items-center gap-2 font-mono text-xs">{items.map((item, index) => <span key={item} className="flex items-center gap-2"><span className="border border-line bg-background px-3 py-2">{item}</span>{index < items.length - 1 && <span className="text-accent">→</span>}</span>)}</div>; }
function SpringGraphic() { return <div className="grid gap-6 md:grid-cols-[.7fr_1.1fr_.8fr] md:items-center"><div className="space-y-2 text-sm text-muted">{["Geometry", "Force", "Lifetime", "Stress", "Manufacturability"].map(item => <div key={item} className="border-l-2 border-accent pl-3">{item}</div>)}</div><div className="border border-line bg-surface p-5"><svg viewBox="0 0 260 180" fill="none" className="w-full text-foreground"><path d="M18 90h36c15-65 30-65 45 0s30 65 45 0 30-65 45 0 30 65 45 0h24" stroke="currentColor" strokeWidth="3" /><path d="M18 35h224M18 145h224" stroke="currentColor" opacity=".35" /></svg><p className="text-center font-mono text-xs text-accent">SEARCH / EVALUATE</p></div><div className="space-y-3">{["Candidate A", "Candidate B", "Candidate C", "Recommended Set"].map((item, index) => <div key={item} className={index === 3 ? "border border-accent p-3 text-sm" : "border border-line p-3 text-sm text-muted"}>{item}</div>)}</div></div>; }
function PartDrawing() { return <div className="grid gap-px border border-line bg-line md:grid-cols-2"><div className="min-h-64 bg-surface p-5"><span className="font-mono text-xs text-accent">3D PART</span><div className="mx-auto mt-10 h-28 w-40 rotate-6 border-2 border-foreground" /></div><div className="min-h-64 bg-background p-5"><span className="font-mono text-xs text-accent">ENGINEERING DRAWING</span><div className="mt-10 border border-foreground p-5"><p className="font-mono text-xs text-muted">REFERENCE → REPLACE → REBUILD</p></div></div></div>; }
const checks = ["Connection", "Template", "Input", "CAD", "Drawing", "Save", "Log", "Engineer Review"];
const contributionGroups = [
  ["01", "ENGINEERING WORKFLOW", "將工程需求、使用者操作與 CAD 更新流程整理為可理解、可執行的自動化流程。"],
  ["02", "DESIGN RULE & PARAMETER SEARCH", "整合設計規則邏輯與參數搜尋流程，支援可公開範圍內的工程判斷。"],
  ["03", "AUTOMATION INTEGRATION", "整合 C# / WinForms 操作流程、SolidWorks API 與模型更新相關作業。"],
  ["04", "VALIDATION & INTEGRATION", "處理流程驗證、例外狀態與紀錄，讓工程師仍能進行確認。"],
] as const;

export function ProbeStory({ previous, next }: { previous: Project; next: Project }) {
  return <main id="main" className="overflow-x-hidden"><header className="mx-auto grid min-h-[82svh] max-w-content items-center gap-10 px-gutter py-section lg:grid-cols-12"><div className="lg:col-span-5"><Link href="/#projects" className="text-sm text-muted hover:text-accent">← Back to Projects</Link><p className="mt-12 font-mono text-xs tracking-widest text-accent">01 / 10 · ENGINEERING WORKFLOW</p><h1 className="mt-6 text-title leading-display tracking-tight">探針自動化系統</h1><p className="mt-4 text-xl text-muted">Probe Automation System</p><p className="mt-8 max-w-md text-lg leading-relaxed">Turning engineering rules into an automated design workflow.</p></div><div className="relative min-h-80 overflow-hidden border border-line bg-surface p-8 lg:col-span-7"><div className="absolute inset-8 border border-line" /><svg viewBox="0 0 520 260" fill="none" className="relative mt-10 w-full text-foreground"><path d="M42 130H478M96 96H424M96 164H424" stroke="currentColor" opacity=".45" /><path d="M130 130c16-62 32-62 48 0s32 62 48 0 32-62 48 0 32 62 48 0 32-62 48 0" stroke="currentColor" strokeWidth="2" /><circle cx="42" cy="130" r="7" fill="currentColor" /><circle cx="478" cy="130" r="7" fill="currentColor" /></svg><p className="absolute bottom-8 left-8 font-mono text-xs text-accent">DESIGN RULE / PARAMETER FLOW</p></div></header><div className="mx-auto max-w-content px-gutter">
      <Stage number="02" title="Before Automation" english="BEFORE AUTOMATION" sentence="Too many repeated engineering steps."><Boxes items={["Engineer", "Check Template", "Modify Parameters", "Open CAD", "Adjust Model", "Update Drawing", "Check Again"]} /></Stage>
      <Stage number="03" title="System Transformation" english="SYSTEM TRANSFORMATION" sentence="Engineering decisions become executable logic."><Boxes items={["Input", "Design Rule", "Parameter Engine", "CAD Automation", "Validation", "Output"]} accent /></Stage>
      <Stage number="04" title="設計規則" english="DESIGN RULE ENGINE" sentence="可標準化的判斷，變成可執行的分支。"><div className="grid gap-5 md:grid-cols-[1fr_auto_1fr] md:items-center"><div className="border border-line p-6"><span className="font-mono text-xs text-accent">INPUT</span><p className="mt-5 text-lg">Part Type?</p></div><span className="text-2xl text-accent">→</span><div className="grid gap-3"><div className="border border-line p-4">Non-SP<br /><span className="text-sm text-muted">Dimension Update</span></div><div className="border border-line p-4">SP Spring<br /><span className="text-sm text-muted">Spring Logic</span></div></div></div></Stage>
      <Stage number="05" title="彈簧參數搜尋" english="SPRING PARAMETER SEARCH" sentence="Search, evaluate, and retain a feasible set."><SpringGraphic /></Stage>
      <Stage number="06" title="CAD 模型自動化" english="CAD AUTOMATION" sentence="參數計算必須真正進入模型。"><div className="grid gap-5 md:grid-cols-[1.2fr_.8fr]"><div className="relative min-h-64 border border-line bg-surface p-5"><div className="absolute inset-10 border border-foreground" /><div className="absolute left-1/4 top-1/3 h-20 w-1/2 -translate-y-1/2 rotate-12 border-2 border-foreground" /><p className="absolute bottom-5 left-5 font-mono text-xs text-accent">CAD MODEL / FEATURE UPDATE</p></div><Flow items={["Selected Parameters", "Dimension Update", "Feature Update", "Rebuild"]} /></div></Stage>
      <Stage number="07" title="零件重生" english="PROBE REBIRTH" sentence="不同零件類型，走不同更新路徑。"><div className="space-y-4"><div className="mx-auto w-fit border border-accent px-6 py-4">Existing Part</div><Flow items={["Non-SP", "Update Dimensions", "Rebuild"]} /><Flow items={["SP Spring", "Apply Parameters", "Rebuild"]} /><div className="mx-auto w-fit border border-accent px-6 py-4">Validated Part</div></div></Stage>
      <Stage number="08" title="零件與工程圖" english="PART + DRAWING" sentence="從既有零件，到新的可追蹤輸出。"><PartDrawing /></Stage>
      <Stage number="09" title="驗證檢查點" english="VALIDATION" sentence="Automation does not remove engineering judgment."><Boxes items={checks} accent /></Stage>
      <Stage number="10" title="Final Output" english="FINAL OUTPUT" sentence="From engineering rules to a repeatable design system."><div className="space-y-8"><Boxes items={["Input", "Design Rule", "Parameter Search", "CAD", "Drawing", "Validation", "Output"]} accent /><div className="grid gap-3 sm:grid-cols-3"><div className="border border-line p-5 text-sm">3D Part</div><div className="border border-line p-5 text-sm">Engineering Drawing</div><div className="border border-line p-5 text-sm">Validation Log</div></div><Boxes items={["Workflow Design", "C# / WinForms", "SolidWorks API", "Design Rule Integration", "Parameter Search Logic", "Validation / Logging"]} /></div></Stage>
      <section className="border-t border-line py-16 md:py-20" aria-labelledby="probe-contribution-title"><div className="grid gap-7 lg:grid-cols-12 lg:gap-12"><div className="lg:col-span-4"><p className="font-mono text-xs tracking-widest text-accent">MY CONTRIBUTION / INDIVIDUAL SCOPE</p><h2 id="probe-contribution-title" className="mt-5 text-heading leading-display tracking-tight">我的貢獻<br /><span className="text-muted">My Contribution</span></h2></div><div className="lg:col-span-8"><div className="grid border-t border-foreground sm:grid-cols-2">{contributionGroups.map(([number, title, detail]) => <article key={number} className="min-h-44 border-b border-line py-5 sm:pr-5 even:sm:border-l even:sm:border-line even:sm:pl-5"><span className="font-mono text-xs text-accent">{number}</span><h3 className="mt-5 text-sm tracking-wide">{title}</h3><p className="mt-3 max-w-sm text-sm leading-loose text-muted">{detail}</p></article>)}</div><p className="mt-6 border-l-2 border-accent pl-4 text-sm leading-relaxed text-muted">PROJECT / SYSTEM SCOPE · CAD / Drawing Automation、參數搜尋與驗證構成整體系統能力；公開頁不揭露內部規則、參數、模板路徑或公司資料。</p></div></div></section>
      <nav aria-label="專案切換" className="grid border-t border-foreground py-10 md:grid-cols-2"><Link href={"/projects/" + previous.slug + "/"} className="py-5 md:pr-8"><span className="text-sm text-muted">← Previous Project</span><p className="mt-4 text-xl">{previous.title}</p><p className="mt-2 text-sm text-muted">{previous.english}</p></Link><Link href={"/projects/" + next.slug + "/"} className="border-t border-line py-5 md:border-t-0 md:border-l md:pl-8 md:text-right"><span className="text-sm text-muted">Next Project →</span><p className="mt-4 text-xl">{next.title}</p><p className="mt-2 text-sm text-muted">{next.english}</p></Link></nav><Link href="/#projects" className="mb-16 inline-block border-b border-foreground py-3 text-sm hover:text-accent" >← Back to Projects</Link></div></main>;
}
