import Link from "next/link";
import type { Project } from "@/data/portfolio";
import { RobotStory } from "./robot-story";

export function RobotProjectDetail({ previous, next }: { previous: Project; next: Project }) {
  return <main id="main">
    <RobotStory />
    <div className="mx-auto max-w-content px-gutter">
      <section className="border-t border-line py-16" aria-labelledby="robot-technologies"><p className="mb-5 font-mono text-xs text-accent">TECHNOLOGIES / 我的設計與研究範圍</p><h2 id="robot-technologies" className="text-heading">Design meets research.</h2><p className="mt-6 max-w-2xl leading-loose text-muted">SolidWorks · Mechanical / Assembly Design · Hardware Placement · Spectrogram · Beat / Tempo / Rhythm Research</p><p className="mt-5 text-sm text-muted">整體團隊系統的元件與工具，請見上方 Project System / Team Components。</p></section>
      <section className="border-t border-line py-16" aria-labelledby="robot-result"><p className="mb-5 font-mono text-xs text-accent">09 / RESULT / CURRENT STAGE</p><h2 id="robot-result" className="text-heading">完成整合，持續探索。</h2><p className="mt-6 max-w-2xl leading-loose text-muted">完成多自由度機器人機構設計、實體製作與系統架構整合，並建立感測、模擬與控制研究基礎。</p><p className="mt-5 max-w-2xl leading-loose text-muted">AI 舞蹈生成仍屬研究與探索階段，主要系統以預先規劃動作序列為主；後續可進一步研究自主動作生成與平衡控制。</p></section><section className="border-t border-line py-16" aria-labelledby="robot-learning"><p className="mb-8 font-mono text-xs text-accent">10 / ENGINEERING LEARNING</p><div className="grid gap-8 md:grid-cols-3"><article><p className="font-mono text-xs text-accent">01</p><h2 className="mt-4 text-xl">Cross-disciplinary Integration</h2><p className="mt-4 text-sm leading-loose text-muted">理解機構、硬體、感測與控制系統之間的關聯。</p></article><article><p className="font-mono text-xs text-accent">02</p><h2 className="mt-4 text-xl">Design for Integration</h2><p className="mt-4 text-sm leading-loose text-muted">機構設計不只考慮幾何外型，也要考慮硬體空間、組裝與控制需求。</p></article><article><p className="font-mono text-xs text-accent">03</p><h2 className="mt-4 text-xl">AI as Engineering Exploration</h2><p className="mt-4 text-sm leading-loose text-muted">從音訊資訊開始理解 AI 如何連結到實際機器人動作，而不是只停留在模型層面。</p></article></div></section>
      <nav aria-label="專案切換" className="grid border-t border-foreground py-10 md:grid-cols-2"><Link href={`/projects/${previous.slug}/`} className="py-5 md:pr-8"><span className="text-sm text-muted">← Previous Project</span><p className="mt-4 text-xl">{previous.title}</p></Link><Link href={`/projects/${next.slug}/`} className="border-t border-line py-5 md:border-t-0 md:border-l md:pl-8 md:text-right"><span className="text-sm text-muted">Next Project →</span><p className="mt-4 text-xl">{next.title}</p></Link></nav>
      <Link href="/#projects" className="mb-16 inline-block border-b border-foreground py-3 text-sm">← Back to Projects</Link>
    </div>
  </main>;
}